version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
volumes:
  gem_cache: